---
  - name: dbtier - install postgres
    yum:
      name: postgresql-server
      state: latest
  - name: dbtier - enable postgres at boot
    service:
      name: postgresql
      enabled: yes
  #- name: tell user to finish setting up postgres
  #  debug:
  #    msg: "Either uncomment the postgres setup or manually login and initialize"

  #only run the next 2 tasks once!
  - name: dbtier - initilize postgres
    command: postgresql-setup initdb
  - name: dbtier - initilize postgres some more
    command: chkconfig postgresql on
  - name: dbtier - start postgres
    service:
      name: postgresql.service
      state: started
